source 'http://rubygems.org'

gem 'rails', '3.2.3'

gem 'execjs'
gem 'therubyracer'
# gem 'rb-readline'

gem 'sqlite3'
gem 'mysql2'
gem 'devise', '2.1.2'
gem 'devise-encryptable'
gem 'simple_form', '2.0.1'
gem 'inherited_resources', '1.3.0'
gem 'slim', '1.2.1'
gem 'country_select', '0.0.1'
gem "liquid", "2.3.0"
gem 'carrierwave', "0.6.2"
gem 'pry', "0.9.8.2"
gem 'pry-nav', "0.1.0"
gem 'pry-stack_explorer', "0.4.1"
gem 'mini_magick', '3.4'
gem "correios-frete", "1.6.1"
gem "plesk-ruby",         git:  "git://github.com/wicz/plesk-ruby.git"
gem "moip-ruby", "0.1.2", git: "git://github.com/bperucchi/moip-ruby.git"
gem "pag_seguro", git: "git://github.com/bperucchi/pagseguro.git"
gem "pagamento_digital", git: "git://github.com/bperucchi/pagamento_digital.git"
gem 'state_machine', '1.1.2'
gem 'ancestry', '1.3.0'

gem 'personhood',     path: '../personhood'
gem 'imentore-core', path: '../imentore-core'
gem 'imentore-auth', path: '../imentore-auth'
gem 'imentore-ecommerce', path: '../imentore-ecommerce'
gem 'imentore-dashboard', path: '../imentore-dashboard'
gem 'imentore-cms', path: '../imentore-cms'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.5'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails', '2.0.2'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', '~> 0.8.3', :require => false
end