source 'http://rubygems.org'

gem 'rails', '3.2.16'

gem 'thin', group: :development
gem 'rb-readline', group: :development

gem "delocalize", '0.3.2'
gem 'execjs'
gem 'therubyracer'
# gem 'rb-readline'

gem 'i18n_alchemy'
gem 'tinymce-rails'
gem 'sqlite3'

gem 'mysql2'

gem 'will_paginate', '3.0.3'
gem 'will_paginate-bootstrap'

gem 'devise', '2.1.2'
gem 'devise-encryptable'
gem 'simple_form', '2.0.3'
gem 'inherited_resources', '1.3.0'
gem 'slim', '1.2.1'
gem 'country_select', '0.0.1'
gem "liquid", "2.6.1"
gem 'carrierwave', "0.6.2"
gem 'pry', "0.9.8.2"
gem 'pry-nav', "0.1.0"
gem 'pry-stack_explorer', "0.4.1"
gem 'mini_magick', '3.4'
gem "correios-frete", "1.6.1"
gem "ruby-plesk",         git:  "git://github.com/bperucchi/ruby-plesk.git"
gem "moip-ruby", "0.1.2", git: "git://github.com/bperucchi/moip-ruby.git"
gem "pag_seguro", "0.1.17", git: "git://github.com/bperucchi/pagseguro.git" 
gem "pagamento_digital", git: "git://github.com/bperucchi/pagamento_digital.git"
gem 'state_machine', '1.2.0'
gem 'ancestry', '1.3.0'

gem "paperclip", :git => "git://github.com/thoughtbot/paperclip.git"


gem 'personhood',     path: '../personhood'
gem 'imentore-core', path: '../imentore-core'
gem 'imentore-auth', path: '../imentore-auth'
gem 'imentore-ecommerce', path: '../imentore-ecommerce'
gem 'imentore-dashboard', path: '../imentore-dashboard'
gem 'imentore-cms', path: '../imentore-cms'
gem 'imentore-admin', path: '../imentore-admin'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.5'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails', '3.1.0'
gem 'jquery-datatables-rails', git: 'git://github.com/rweng/jquery-datatables-rails.git'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
gem 'capistrano', '3.2.1'
gem 'capistrano-rbenv', '~> 2.0'
gem 'capistrano-bundler', '1.1.2'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', '~> 0.8.3', :require => false
end