source "http://rubygems.org"

gem 'rails', '4.0.13'

gemspec


group :test, :development do

  gem "imentore-core",  path: "../imentore-core"
  gem "imentore-cms",  path: "../imentore-cms"
  gem "imentore-ecommerce",  path: "../imentore-ecommerce"
  gem "imentore-auth",  path: "../imentore-auth"
  gem "imentore-dashboard",  path: "../imentore-dashboard"
  gem "imentore-manager",  path: "../imentore-manager"
  gem "personhood",     path: "../personhood"
  gem 'simple_form', '3.1.0'
  gem "slim-rails"
  gem "paranoia", "~> 2.0"
  gem 'inherited_resources', '1.6.0'
  gem 'devise', '3.5.1'
  gem 'devise-encryptable'
  gem 'ancestry', '2.1.0'
  gem 'jquery-rails', '3.1.3'
  gem 'jquery-datatables-rails', '3.3.0'
  gem 'jquery-ui-rails', '5.0.5'
  gem 'state_machine', '1.2.0'


  gem 'pry', "0.10.3"
  gem 'pry-remote', "0.1.7"
  gem 'pry-byebug', "3.3.0"
  gem 'pry-meta'
  gem 'pry-stack_explorer', "0.4.9.2"

  gem 'rspec-rails', "3.4.1"
  gem 'test-unit'
  gem 'guard-rspec'
  gem 'rb-fsevent' if `uname` =~ /Darwin/
  # gem "guard-cucumber", "0.7.5"
  gem "shoulda-matchers", "1.0.0"
  gem "database_cleaner", "1.5.1"
  # gem "cucumber-rails", "1.3.0"
  gem "factory_girl_rails", "4.5.0"
  gem "capybara", "2.6.2"
  gem "capybara-webkit", "1.8.0"
  gem 'launchy', "2.4.3"
  gem 'fabrication'
end
