source "http://rubygems.org"

# Declare your gem's dependencies in imentore-store.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# jquery-rails is used by the dummy application
gem "jquery-rails"

gem 'inherited_resources', '1.3.0'

gem 'devise', '1.5.3'
gem 'simple_form', '1.5.2'
gem 'slim', '1.1.0'

gem 'imentore-core',  path: '../imentore-core'
gem 'imentore-user',  path: '../imentore-user'
gem 'personhood',     path: '../personhood'

group :test, :development do
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'cucumber-rails'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'pry'
  gem 'ruby-debug19'
end