source "http://rubygems.org"

# Declare your gem's dependencies in imentore-store.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# jquery-rails is used by the dummy application
gem "jquery-rails"

gem 'inherited_resources', '1.3.0'

gem 'devise', '1.5.3'
gem 'simple_form', '1.5.2'
gem 'slim', '1.1.0'

gem 'imentore-site',  path: '../imentore-site'
gem 'imentore-user',  path: '../imentore-user'
gem 'personhood',     path: '../personhood'

group :test, :development do
  gem 'guard-rspec'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'pry'
end

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'ruby-debug'
