source "http://rubygems.org"

# Declare your gem's dependencies in imentore-core.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# jquery-rails is used by the dummy application
gem "jquery-rails"

gem 'simple_form', '1.5.2'
gem 'slim', '1.1.0'
gem 'country_select', '0.0.1'

group :test, :development do
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'cucumber-rails'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'pry'
  gem 'ruby-debug19'
end