source "http://rubygems.org"

# Declare your gem's dependencies in imentore-core.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# jquery-rails is used by the dummy application
gem "jquery-rails", '2.0.2'

gem 'inherited_resources', '1.3.0'
gem 'devise', "3.3.0"
gem 'simple_form', '2.0.3'
gem 'slim', '1.2.1'

gem 'imentore-auth',  path: '../imentore-auth'
gem 'imentore-ecommerce',  path: '../imentore-ecommerce'
gem 'imentore-cms',  path: '../imentore-cms'
gem 'personhood',     path: '../personhood'

group :test, :development do
  gem 'guard-rspec', "0.6.0"
  gem 'guard-cucumber', "0.7.5"
  # gem 'rspec-rails', "2.8.1"
  gem 'shoulda-matchers', "1.0.0"
  gem 'database_cleaner', "0.7.1"
  gem 'cucumber-rails', "1.3.0"
  gem 'factory_girl_rails', "1.7.0"
  gem 'capybara', "1.1.2"
  gem 'capybara-webkit', "0.10.0"
  gem 'pry', "0.10.1"
  gem 'pry-nav', "0.2.4"
  gem 'pry-stack_explorer', "0.4.9.1"
  gem 'imentore-testing',  path: '../imentore-testing'
end
