source "http://rubygems.org"

gemspec

gem "ruby-plesk",         git:  "git://github.com/bperucchi/ruby-plesk.git"
gem "imentore-core",  path: "../imentore-core"
gem "imentore-ecommerce",  path: "../imentore-ecommerce"
gem "imentore-auth",  path: "../imentore-auth"
gem "imentore-dashboard",  path: "../imentore-dashboard"
gem "personhood",     path: "../personhood"

group :test, :development do
  # gem "guard-rspec", "0.6.0"
  # gem "guard-cucumber", "0.7.5"
  # gem "rspec-rails", "2.8.1"
  # gem "shoulda-matchers", "1.0.0"
  # gem "database_cleaner", "0.7.1"
  # gem "cucumber-rails", "1.3.0"
  # gem "factory_girl_rails", "1.7.0"
  # gem "capybara", "2.3.0"
  # gem "capybara-webkit", "1.5.2"
  # gem "pry", "0.10.1"
  # gem "pry-nav", "0.2.4"
  # gem "pry-stack_explorer", "0.4.9.1"
  gem "imentore-testing",  path: "../imentore-testing"
end
