source "http://rubygems.org"

# Declare your gem's dependencies in imentore-dashboard.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

gem 'devise', '2.0.4'
gem 'simple_form', '2.0.1'
gem 'slim', '1.1.0'
gem 'inherited_resources', '1.3.0'

gem 'imentore-core',  path: '../imentore-core'
gem 'imentore-ecommerce',  path: '../imentore-ecommerce'
gem 'imentore-auth',  path: '../imentore-auth'
gem 'imentore-cms',  path: '../imentore-cms'
gem 'personhood',     path: '../personhood'
gem "plesk-ruby",         git:  "git://github.com/wicz/plesk-ruby.git"

group :test, :development do
  gem 'guard-rspec', "0.6.0"
  gem 'guard-cucumber', "0.7.5"
  gem 'rspec-rails', "2.8.1"
  gem 'shoulda-matchers', "1.0.0"
  gem 'database_cleaner', "0.7.1"
  gem 'cucumber-rails', "1.3.0"
  gem 'factory_girl_rails', "1.7.0"
  gem 'capybara', "1.1.2"
  gem 'capybara-webkit', "0.10.0"
  gem 'pry', "0.9.8.2"
  gem 'pry-nav', "0.1.0"
  gem 'pry-stack_explorer', "0.4.1"
  gem 'imentore-testing',  path: '../imentore-testing'
end

# jquery-rails is used by the dummy application
gem "jquery-rails"

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
