source "http://rubygems.org"

# Declare your gem's dependencies in imentore-dashboard.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

gem 'devise', '1.5.3'
gem 'simple_form', '1.5.2'
gem 'slim', '1.1.0'
gem 'inherited_resources', '1.3.0'

gem 'imentore-core',  path: '../imentore-core'
gem 'imentore-store',  path: '../imentore-store'
gem 'personhood',     path: '../personhood'

group :test, :development do
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'cucumber-rails'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'pry'
  gem 'ruby-debug19'
  gem 'imentore-testing',  path: '../imentore-testing'
end

# jquery-rails is used by the dummy application
gem "jquery-rails"

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
