source "http://rubygems.org"

gemspec

# jquery-rails is used by the dummy application
gem 'jquery-rails', '3.1.3'

gem 'inherited_resources', '1.6.0'
gem "devise", "3.5.1"
gem 'devise-encryptable'
gem "simple_form", "3.1.0"
gem 'slim-rails'
gem "country_select", "0.0.1"
gem "liquid", "3.0.3"
gem "correios-frete", "1.6.1"
gem 'ancestry', '2.1.0'

gem "imentore-core",      path: "../imentore-core"
gem "imentore-auth",      path: "../imentore-auth"
gem "imentore-dashboard", path: "../imentore-dashboard"
gem "imentore-cms",       path: "../imentore-cms"
gem 'imentore-manager',   path: '../imentore-manager'
gem "personhood",         path: "../personhood"
# gem "ruby-plesk",         git:  "git://github.com/bperucchi/ruby-plesk.git"


group :test, :development do
  gem 'rspec-rails', "3.4.1"
  gem 'test-unit'
  # gem "guard-rspec", "0.6.0"
  # gem "guard-cucumber", "0.7.5"
  gem "shoulda-matchers", "1.0.0"
  gem "database_cleaner", "1.5.1"
  # gem "cucumber-rails", "1.3.0"
  gem "factory_girl_rails", "4.5.0"
  # gem "capybara", "2.5.0"
  # gem "capybara-webkit"
  gem 'pry', "0.10.3"
  gem 'pry-byebug', "3.3.0"
  # gem 'pry-debugger'
  # gem 'pry-remote', "0.1.7"
  gem 'fabrication'
  gem "imentore-testing",  path: "../imentore-testing"
end
