source "http://rubygems.org"

gemspec

# jquery-rails is used by the dummy application
gem "jquery-rails", '2.0.2'

gem "inherited_resources", "1.3.0"
gem "devise", "2.1.2"
gem "simple_form", "2.0.1"
gem 'slim', '1.2.1'
gem "country_select", "0.0.1"
gem "liquid", "2.4.1"
gem "correios-frete", "1.6.1"

gem "imentore-core",      path: "../imentore-core"
gem "imentore-auth",      path: "../imentore-auth"
gem "imentore-dashboard", path: "../imentore-dashboard"
gem "imentore-cms",       path: "../imentore-cms"
gem "personhood",         path: "../personhood"
gem "ruby-plesk",         git:  "git://github.com/bperucchi/ruby-plesk.git"


group :test, :development do
  gem "guard-rspec", "0.6.0"
  gem "guard-cucumber", "0.7.5"
  gem "rspec-rails", "2.8.1"
  gem "shoulda-matchers", "1.0.0"
  gem "database_cleaner", "0.7.1"
  gem "cucumber-rails", "1.3.0"
  gem "factory_girl_rails", "1.7.0"
  gem "capybara", "1.1.2"
  gem "capybara-webkit", "0.10.0"
  gem "pry", "0.9.8.2"
  gem "pry-nav", "0.1.0"
  gem "pry-stack_explorer", "0.4.1"
  gem "imentore-testing",  path: "../imentore-testing"
end
